### PR TITLE
New Option: Cursor Scope in Indent Mode

### PR DESCRIPTION
**Pull request by shaunlebron**
In preparation for auto-indent in atom-parinfer, I started understanding the problem space around new line insertion, and ended up formalizing a simple new cursor rule that can help UX.

If `previewCursorScope` is enabled in Indent Mode, then this...

``` clj
(let [foo 1
       bar 2])
  |
```

...will look like this:

``` clj
(let [foo 1
       bar 2]
  |)
```

I thought about this last year and didn't think it could be done in a manner consistent to Parinfer's rules. But it seems solid now.  [Full details in new design doc section](https://github.com/shaunlebron/parinfer/blob/cursor-scope/lib/parinfer.js.md#seeing-cursor-scope-in-indent-mode)

_This will also enable easier drawing in the Parinfer Next experiment._

### CODE REVIEW

**Comment by shaunlebron** [comment]
@oakmac (made this a pull request if you want to review; thanks again for offering)

**Comment by shaunlebron** [comment]
@oakmac Try this out here to get a feel for it: http://shaunlebron.github.io/parinfer/demo

**Comment by shaunlebron** [comment]
Merging this tomorrow night

**Comment by oakmac** [comment]
We had a hangout about this tonight. Summarizing discussion below:
- consider changing `previewCursorScope` to `cursorPreview`
- only show the cursor preview if parens would be displayed after the cursor. ie: do not show paren preview "inside" an expression
- it's confusing to see parens modfied on the previous line as opposed to the current line you are on. demo: take a [large expression](https://github.com/oakmac/tourney-bot/blob/master/cljs-shared/tourneybot/data.cljs#L185-L231) with lines that only contain comments, move the cursor to column 0, and move up and down through the expression. the result on comment-only lines is jarring

**Comment by oakmac** [comment]
here's the demo expression we used for testing: https://github.com/oakmac/tourney-bot/blob/master/cljs-shared/tourneybot/data.cljs#L185-L231

**Comment by oakmac** [comment]
Unanswered question of whether or not this should be the default behavior of Parinfer in Indent Mode, or only enabled via config.

**Comment by shaunlebron** [comment]
After more thinking, we should only do this when it is _nondestructive to the AST_.  This goal is somehow inline with our intuition of only wanting to preview the parens if they are appended to the cursor.  Insane.

For example, suppose we have the cursor here:

``` clj
(let [a 1
      b 2]
      |
 (+ a b))
```

Showing cursor scope would not modify the AST:

``` clj
(let [a 1
      b 2
      |]
 (+ a b))
```

But placing the cursor at the start of the line _will_ modify the AST:

``` clj
(let [a 1
      b 2])
|
 (+ a b)
```

Formal definition: only preview if the cursor is to the right of the next indentation point.

**Comment by shaunlebron** [comment]
Implemented the discussed changes, you can try at the [demo site](http://shaunlebron.github.io/parinfer/demo).

I won't merge until I decide whether this is default behavior.  I'm leaning towards yes, but I'll ask around first, and make appropriate changes here if we commit to this being default.

**Pull request merged**
